### ISSUE TITLE
UniTask package not recognized in Unity 2020.3.5f1

### ISSUE THREAD

**Issue by ns2808** [Cysharp/UniTask#269] opened 2021-04-25 15:46 UTC
Hi,

UniTask is the only Git package that doesn't get recognised by Visual Studio in my project. I have tried to delete and regenerate project files, update Visual Studio, remove and reimport UniTask etc. but nothing seems to work.

* Unity 2020.3.5f1
* Visual Studio Editor package version: 2.0.7 (latest and Verified)
* UniTask version 2.2.5

The "using Cysharp.Threading.Tasks;" line at the top of my files in Visual Studio is greyed out although the project compiles just fine in Unity.

**Comment by guitarrapc** [comment] 2021-04-26 10:03
Thank you for reporting. I've investigate and identify an issue is known as Unity regression since 2020.3.2f1 and 2019.4.24f1.

> [Unity Issue Tracker \- Package resolution error when using a Git dependency referencing an annotated tag in its Git URL](https://issuetracker.unity3d.com/issues/package-resolution-error-when-using-a-git-dependency-referencing-an-annotated-tag-in-its-git-url?_ga=2.164640191.1854444799.1619404631-1321912765.1607477419)

Unfortunately there are no workaround for UPM + git for UniTask, as UniTask is using annotation for git url path.
Hopefully Unity note `RESOLUTION NOTE (FIX VERSION 2021.2): Fixed in 2021.2.0a15`, I believe it will fix in near future verseion.

Please use UnityPackage or OpenUPM to install package, or Downgrade Unity if possible.
Thanks,

**Comment by ns2808** [comment] 2021-04-26 22:03
Hello,

I had tried both actually (installing with UPM + Git and installing with the .unitypackage).

The annoying part is that Unity itself seems to recognize UniTask just fine (the game runs properly). It has to do with Visual Studio.

Not sure why UniTask in particular but all the other packages do get recognized in Visual Studio. Maybe something with the Visual Studio Editor package in Unity?

**Comment by guitarrapc** [comment] 2021-04-27 01:10
Is your Sln shows UniTask on SolutionExplorer?
![image](https://user-images.githubusercontent.com/3856350/116169948-c3397400-a740-11eb-9c95-cf57a1842125.png)

Is your Assembly-CSharp > References contains UniTask?
![image](https://user-images.githubusercontent.com/3856350/116169929-bd439300-a740-11eb-8549-4dac010a5534.png)

**Comment by KichangKim** [comment] 2021-04-27 02:10
If you want to use Visual studio (ex, intellisense) for packages, you should enable "Generate csproj option" in Preference settings.

https://forum.unity.com/threads/searching-code-in-package-manager-from-visual-studio.545840/#post-5612848

**Comment by guitarrapc** [comment] 2021-04-27 02:49
Thanks, there's no reference issue for package on Unity 2020.3.1f1.
![image](https://user-images.githubusercontent.com/3856350/116177042-1b2aa780-a74e-11eb-95e8-6db524159855.png)

Is your project could load UniTask even [2020.3.5f1 hasUnity regression](https://issuetracker.unity3d.com/issues/package-resolution-error-when-using-a-git-dependency-referencing-an-annotated-tag-in-its-git-url?_ga=2.164640191.1854444799.1619404631-1321912765.1607477419)?

**Comment by ns2808** [comment] 2021-04-27 10:58
Alright guys, solved. Thanks a lot for your help.

I did what guitarrapc suggested: I went into the Solution Explorer and I saw that a bunch of the projects (or whatever they are) listed had "(Unavailable)" next to them. I then right-clicked on each of them and clicked "Reload".

This did solve the problem for UniTask however another package I use started having the same issue after that so I once again deleted all csproj files from my project folder, navigated to Unity > Preferences > External Tools and clicked on "Regenerate project files".

Re your UPM + Git question, it works in 2020.3.5f1 for me (although right now I managed to make it work with my .unitypackage installation so I won't touch it again!).

**Comment by guitarrapc** [comment] 2021-06-29 02:38
Issue updated. 
> https://issuetracker.unity3d.com/issues/package-resolution-error-when-using-a-git-dependency-referencing-an-annotated-tag-in-its-git-url?_ga=2.164640191.1854444799.1619404631-1321912765.1607477419

RESOLUTION NOTE (FIX VERSION 2021.2):
Fixed in 2021.2.0a15

RESOLUTION NOTE (FIX VERSION 2021.1):
Fixed in: 2021.1.5f1

RESOLUTION NOTE (FIX VERSION 2020.3):
Fixed in 2020.3.11f1

RESOLUTION NOTE (FIX VERSION 2019.4):
Fixed in 2019.4.28f1

**Comment by guitarrapc** [comment] 2021-06-29 02:38
Let's close case.

**Closed by guitarrapc** 2021-06-29 02:38 UTC
